services:
    portfolio:
        container_name: portfolio
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true
